name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - feature-branchA
      - main

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Config Files
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.1.7"
      
      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform
      
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./Terraform
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./Terraform
      
      - name: terraform apply or destroy 
        run: |
          if [ "${{ github.event.inputs.destroy }}" = "yes" ]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi
        working-directory: ./Terraform